/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;


// * TODO: Create Class.
// * TODO: add invertColor method.
// * TODO: add randomizeColor method.
// * TODO: add saveFile method.
// * TODO: create CLI App.
// * TODO: add Black and white method.

public class App {

    public static void main(String[] args) {

//Bitmap img = new Bitmap("src/main/resources/java.bmp", "src");
//        img.blackAndWhite();
//        img.saveImg();
//       System.out.println(img.getImg().createGraphics());
        if (args.length == 3) {
            Bitmap img = new Bitmap(args[0], args[1]);
            switch (args[2].toLowerCase()) {
                case "invert":
                    img.invert();
                    img.saveImg();
                    break;
                case "random":
                    img.randomize();
                    img.saveImg();
                    break;
                case "blackandwhite":
                    img.blackAndWhite();
                    img.saveImg();
                    break;
                default:
                    System.out.println("You Entered an error method name please write it in the correct way");
                    System.out.println("method names are");
                    System.out.println("[invert, random,blackandwhite]");
                    
            }
        } else {
            System.out.println("You Entered the normal mode for editing your img");
        }

    }


}
